// Code generated by MockGen. DO NOT EDIT.
// Source: session_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSessionHandler is a mock of SessionHandler interface
type MockSessionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSessionHandlerMockRecorder
}

// MockSessionHandlerMockRecorder is the mock recorder for MockSessionHandler
type MockSessionHandlerMockRecorder struct {
	mock *MockSessionHandler
}

// NewMockSessionHandler creates a new mock instance
func NewMockSessionHandler(ctrl *gomock.Controller) *MockSessionHandler {
	mock := &MockSessionHandler{ctrl: ctrl}
	mock.recorder = &MockSessionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionHandler) EXPECT() *MockSessionHandlerMockRecorder {
	return m.recorder
}

// Open mocks base method
func (m *MockSessionHandler) Open(savePath, sessionName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", savePath, sessionName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Open indicates an expected call of Open
func (mr *MockSessionHandlerMockRecorder) Open(savePath, sessionName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSessionHandler)(nil).Open), savePath, sessionName)
}

// Close mocks base method
func (m *MockSessionHandler) Close() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSessionHandlerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessionHandler)(nil).Close))
}

// Gc mocks base method
func (m *MockSessionHandler) Gc(maxLifeTime int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gc", maxLifeTime)
	ret0, _ := ret[0].(int)
	return ret0
}

// Gc indicates an expected call of Gc
func (mr *MockSessionHandlerMockRecorder) Gc(maxLifeTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gc", reflect.TypeOf((*MockSessionHandler)(nil).Gc), maxLifeTime)
}

// Read mocks base method
func (m *MockSessionHandler) Read(sessionID string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", sessionID)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Read indicates an expected call of Read
func (mr *MockSessionHandlerMockRecorder) Read(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockSessionHandler)(nil).Read), sessionID)
}

// Write mocks base method
func (m *MockSessionHandler) Write(sessionID string, sessionData interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", sessionID, sessionData)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockSessionHandlerMockRecorder) Write(sessionID, sessionData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSessionHandler)(nil).Write), sessionID, sessionData)
}
