// Code generated by MockGen. DO NOT EDIT.
// Source: session_id_creator.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSessionIDCreator is a mock of SessionIDCreator interface
type MockSessionIDCreator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionIDCreatorMockRecorder
}

// MockSessionIDCreatorMockRecorder is the mock recorder for MockSessionIDCreator
type MockSessionIDCreatorMockRecorder struct {
	mock *MockSessionIDCreator
}

// NewMockSessionIDCreator creates a new mock instance
func NewMockSessionIDCreator(ctrl *gomock.Controller) *MockSessionIDCreator {
	mock := &MockSessionIDCreator{ctrl: ctrl}
	mock.recorder = &MockSessionIDCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionIDCreator) EXPECT() *MockSessionIDCreatorMockRecorder {
	return m.recorder
}

// CreateSID mocks base method
func (m *MockSessionIDCreator) CreateSID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSID")
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateSID indicates an expected call of CreateSID
func (mr *MockSessionIDCreatorMockRecorder) CreateSID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSID", reflect.TypeOf((*MockSessionIDCreator)(nil).CreateSID))
}
